# Generated by Django 5.2.6 on 2025-09-24 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_en", models.CharField(max_length=100, unique=True)),
                ("name_ko", models.CharField(max_length=100, unique=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="brand_logos/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("website", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="WatchModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_number", models.CharField(max_length=100)),
                ("nickname", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="watch_models/"),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="models",
                        to="api.brand",
                    ),
                ),
            ],
            options={
                "unique_together": {("brand", "model_number", "nickname")},
            },
        ),
        migrations.CreateModel(
            name="WatchVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color", models.CharField(max_length=50)),
                ("color_code", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="watch_variants/"
                    ),
                ),
                (
                    "watch_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="api.watchmodel",
                    ),
                ),
            ],
            options={
                "unique_together": {("watch_model", "color")},
            },
        ),
        migrations.CreateModel(
            name="WatchTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("sell", "판매"), ("buy", "매입")], max_length=10
                    ),
                ),
                ("country", models.CharField(max_length=100)),
                ("currency", models.CharField(default="KRW", max_length=10)),
                ("price", models.DecimalField(decimal_places=2, max_digits=15)),
                ("url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "watch_variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="api.watchvariant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WatchPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("price", models.PositiveIntegerField()),
                ("url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="api.vendor",
                    ),
                ),
                (
                    "watch_variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="api.watchvariant",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["year"], name="api_watchpr_year_9ac241_idx"),
                    models.Index(
                        fields=["vendor"], name="api_watchpr_vendor__f45729_idx"
                    ),
                ],
                "unique_together": {("watch_variant", "vendor", "year")},
            },
        ),
    ]
