# Generated by Django 5.2.6 on 2025-09-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchtransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[("sell", "판매가"), ("buy", "매입가")], max_length=10
            ),
        ),
    ]
