# Generated by Django 5.2.6 on 2025-09-24 19:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_watchtransaction_transaction_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_kr", models.CharField(max_length=100, unique=True)),
                ("name_en", models.CharField(max_length=100, unique=True)),
                (
                    "iso2",
                    models.CharField(
                        max_length=2,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Za-z]{2}$", "ISO2 (예: KR, US)"
                            )
                        ],
                    ),
                ),
                (
                    "flag",
                    models.ImageField(
                        blank=True, null=True, upload_to="country_flags/"
                    ),
                ),
                (
                    "default_currency",
                    models.CharField(
                        blank=True,
                        max_length=3,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Za-z]{3}$", "통화코드 (예: KRW, USD)"
                            )
                        ],
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="watchtransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[("sell", "판매"), ("buy", "매입")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="watchtransaction",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="api.country",
            ),
        ),
    ]
