# Generated by Django 5.2.6 on 2025-09-24 19:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_country_alter_watchtransaction_transaction_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base",
                    models.CharField(
                        db_index=True,
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator("^[A-Za-z]{3}$")
                        ],
                    ),
                ),
                (
                    "quote",
                    models.CharField(
                        db_index=True,
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator("^[A-Za-z]{3}$")
                        ],
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("rate", models.DecimalField(decimal_places=8, max_digits=18)),
                ("source", models.CharField(default="manual", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date", "base", "quote"],
                "indexes": [
                    models.Index(
                        fields=["date", "base", "quote"],
                        name="api_exchang_date_063ce6_idx",
                    )
                ],
                "unique_together": {("base", "quote", "date")},
            },
        ),
    ]
