# Generated by Django 5.2.6 on 2025-09-24 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_exchangerate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchtransaction",
            name="currency",
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
