# Generated by Django 5.2.6 on 2025-09-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_watchtransaction_currency"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="watchvariant",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="watchvariant",
            name="model_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="watchvariant",
            name="color",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="watchmodel",
            unique_together={("brand", "nickname")},
        ),
        migrations.AlterUniqueTogether(
            name="watchvariant",
            unique_together={("watch_model", "model_number")},
        ),
    ]
