# Generated by Django 5.2.6 on 2025-09-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_move_model_number_to_variant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="watchmodel",
            name="model_number",
        ),
        migrations.AlterField(
            model_name="watchvariant",
            name="model_number",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
