# Generated by Django 5.2.6 on 2025-09-25 21:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_remove_watchmodel_model_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="watchtransaction",
            name="price_max",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="watchtransaction",
            name="price_min",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="watchtransaction",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
    ]
