# Generated by Django 5.2.6 on 2025-09-25 21:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_watchtransaction_price_max_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="watchtransaction",
            name="note",
            field=models.TextField(blank=True, help_text="특이사항/상태/구성품 등", null=True),
        ),
    ]
