# Generated by Django 5.2.6 on 2025-09-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="approval_status",
            field=models.CharField(
                choices=[("pending", "승인대기"), ("approved", "승인완료"), ("rejected", "반려")],
                default="approved",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("operator", "운영자"), ("dealer", "딜러"), ("user", "일반인")],
                default="user",
                max_length=16,
            ),
        ),
    ]
